# Generated by Django 4.2.23 on 2025-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
